### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by shamal69** [simonhq/canberradams#2]
Hi

I have followed all of the instructions here, including adding AppDaemon4 from the store, but cannot get this application to start.

Have included:
appdaemon:
  system_packages: []
  python_packages:
    - xmltodict
  init_commands: []
 into /config/appdaemon/appdaemon.yaml file.

AppDaemon4 log is recursively logging:
[14:18:55] INFO: Starting AppDaemon...
2020-05-06 14:18:56.205492 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-05-06 14:18:56.205665 INFO AppDaemon: Python version is 3.8.2
2020-05-06 14:18:56.205810 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-05-06 14:18:56.206559 INFO AppDaemon: Added log: AppDaemon
2020-05-06 14:18:56.206679 INFO AppDaemon: Added log: Error
2020-05-06 14:18:56.206819 INFO AppDaemon: Added log: Access
2020-05-06 14:18:56.206989 INFO AppDaemon: Added log: Diag
2020-05-06 14:18:56.207118 ERROR AppDaemon: time_zone not specified in appdaemon.cfg
2020-05-06 14:18:56.207241 ERROR AppDaemon: latitude not specified in appdaemon.cfg
2020-05-06 14:18:56.207362 ERROR AppDaemon: longitude not specified in appdaemon.cfg
2020-05-06 14:18:56.207485 ERROR AppDaemon: elevation not specified in appdaemon.cfg

I have included following lines in configuration.yaml:
canberra_dams:
  module: canberradams
  class: Get_ACT_Dams
  DAM_FLAG: "input_boolean.check_dams"

Absolute noob here, so it's obviously something I missing or doing wrong ... any help greatly appreciated.

Thanks in advance

**Comment by simonhq** [comment]
Hi shamal69, 

No problems, let me walk you through a couple of the concepts;

once you install appdaemon you will have a few extra folders in your configuration,

In your appdaemon folder you will have an appdaemon.yaml file that you will need to complete with your latitude and longitude and timezone etc. - do a search for the Appdaemon 4 documentation and there will be a setup guide on what to put in there. But the information you have put in there doesn't go there - it goes in the supervisor panel of home assistant (I have included a picture).
![appdaemon_config](https://user-images.githubusercontent.com/18653928/81140777-fa51cb00-8fad-11ea-94ec-e6d5465963e9.PNG)

In your configuration you will need to create the input_boolean.check_dams (I think you can set it up as a helper in the UI now, but I haven't tried that yet).

Once you have done that, you will also have a appdaemon/apps folder with an apps.yaml file and that is where you put the information that you have put in your configuration.yaml file.  Again the appdaemon docs will show more details if you need them.

So rough steps:

* appdaemon supervisor panel - includes for extra packages
* appdaemon.yaml - nothing special for this app
* apps.yaml - the app info about canberra_dams

Hope this helps - let me know how you go

Simon

**Comment by shamal69** [comment]
Hi Simon

Thanks for the reply - I am leaving this on a public forum as it may help someone else like me in the future.

I did all of the above and have the following result.  The app is still not starting:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.5
 You are running the latest version of this add-on.
 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.9
 Home Assistant Supervisor: 220
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting bs4
  Downloading https://wheels.hass.io/alpine-3.11/amd64/bs4-0.0.1-py3-none-any.whl
Collecting beautifulsoup4 (from bs4)
  Downloading https://files.pythonhosted.org/packages/e8/b5/7bb03a696f2c9b7af792a8f51b82974e51c268f15e925fc834876a4efa0b/beautifulsoup4-4.9.0-py3-none-any.whl (109kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4)
  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4, bs4
Successfully installed beautifulsoup4-4.9.0 bs4-0.0.1 soupsieve-2.0
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Installing collected packages: xmltodict
Successfully installed xmltodict-0.12.0
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:18:16] INFO: Starting AppDaemon...
2020-05-06 16:18:17.991939 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-05-06 16:18:17.992162 INFO AppDaemon: Python version is 3.8.2
2020-05-06 16:18:17.993164 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-05-06 16:18:17.993693 INFO AppDaemon: Added log: AppDaemon
2020-05-06 16:18:17.994017 INFO AppDaemon: Added log: Error
2020-05-06 16:18:17.994542 INFO AppDaemon: Added log: Access
2020-05-06 16:18:17.995345 INFO AppDaemon: Added log: Diag
2020-05-06 16:18:18.031399 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-05-06 16:18:18.076481 INFO HASS: HASS Plugin Initializing
2020-05-06 16:18:18.077288 INFO HASS: HASS Plugin initialization complete
2020-05-06 16:18:18.079563 INFO AppDaemon: HTTP is disabled
2020-05-06 16:18:18.094991 INFO HASS: Connected to Home Assistant 0.108.9
2020-05-06 16:18:18.108385 INFO AppDaemon: App 'canberra_dams' added
2020-05-06 16:18:18.110627 INFO AppDaemon: Found 1 total apps
2020-05-06 16:18:18.112005 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2020-05-06 16:18:18.144417 INFO HASS: Evaluating startup conditions
2020-05-06 16:18:18.172478 INFO AppDaemon: Got initial state from namespace default
2020-05-06 16:18:20.119234 INFO AppDaemon: Scheduler running in realtime
2020-05-06 16:18:20.124925 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-05-06 16:18:20.126890 INFO AppDaemon: Adding /config/appdaemon/apps/config-check to module import path
2020-05-06 16:18:20.128812 INFO AppDaemon: Adding /config/appdaemon/apps/canberradams to module import path
2020-05-06 16:18:20.139666 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/config-check/checkconfig.py - ignoring
2020-05-06 16:18:20.142877 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/canberradams/canberradams.py
2020-05-06 16:18:20.172791 WARNING Error: ------------------------------------------------------------
2020-05-06 16:18:20.174619 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/canberradams/canberradams.py:
2020-05-06 16:18:20.176050 WARNING Error: ------------------------------------------------------------
2020-05-06 16:18:20.182336 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/canberradams/canberradams.py", line 33, in <module>
    import globals
ModuleNotFoundError: No module named 'globals'
2020-05-06 16:18:20.183983 WARNING Error: ------------------------------------------------------------
2020-05-06 16:18:20.186210 WARNING AppDaemon: Removing associated apps:
2020-05-06 16:18:20.188347 WARNING AppDaemon: canberra_dams
2020-05-06 16:18:20.190160 INFO AppDaemon: App initialization complete


Much further along than before though ... thank you

**Comment by simonhq** [comment]
Hi shamal69,

I just implemented a change to remove the requirements for globals.py, give it a go hopefully it should now work.

Thanks

Simon

**Comment by shamal69** [comment]
Hi Simon

There still appears to be an error when initialising the application.  I have applied the latest update (725a77a)

Here is the log file for Appdaemon4:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.5
 You are running the latest version of this add-on.
 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.109.6
 Home Assistant Supervisor: 221
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting bs4
  Downloading https://wheels.hass.io/alpine-3.11/amd64/bs4-0.0.1-py3-none-any.whl
Collecting beautifulsoup4 (from bs4)
  Downloading https://files.pythonhosted.org/packages/e8/b5/7bb03a696f2c9b7af792a8f51b82974e51c268f15e925fc834876a4efa0b/beautifulsoup4-4.9.0-py3-none-any.whl (109kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4)
  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4, bs4
Successfully installed beautifulsoup4-4.9.0 bs4-0.0.1 soupsieve-2.0
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Installing collected packages: xmltodict
Successfully installed xmltodict-0.12.0
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03:07:37] INFO: Starting AppDaemon...
2020-05-09 03:07:38.450088 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-05-09 03:07:38.450309 INFO AppDaemon: Python version is 3.8.2
2020-05-09 03:07:38.450575 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-05-09 03:07:38.450817 INFO AppDaemon: Added log: AppDaemon
2020-05-09 03:07:38.450968 INFO AppDaemon: Added log: Error
2020-05-09 03:07:38.451108 INFO AppDaemon: Added log: Access
2020-05-09 03:07:38.451268 INFO AppDaemon: Added log: Diag
2020-05-09 03:07:38.472070 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-05-09 03:07:38.502796 INFO HASS: HASS Plugin Initializing
2020-05-09 03:07:38.503109 INFO HASS: HASS Plugin initialization complete
2020-05-09 03:07:38.503990 INFO AppDaemon: HTTP is disabled
2020-05-09 03:07:38.511910 INFO HASS: Connected to Home Assistant 0.109.6
2020-05-09 03:07:38.531064 INFO AppDaemon: App 'canberra_dams' added
2020-05-09 03:07:38.532146 INFO AppDaemon: Found 1 total apps
2020-05-09 03:07:38.532797 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2020-05-09 03:07:38.538980 INFO HASS: Evaluating startup conditions
2020-05-09 03:07:38.550332 INFO AppDaemon: Got initial state from namespace default
2020-05-09 03:07:40.539165 INFO AppDaemon: Scheduler running in realtime
2020-05-09 03:07:40.541575 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-05-09 03:07:40.542231 INFO AppDaemon: Adding /config/appdaemon/apps/config-check to module import path
2020-05-09 03:07:40.542907 INFO AppDaemon: Adding /config/appdaemon/apps/canberradams to module import path
2020-05-09 03:07:40.545375 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/config-check/checkconfig.py - ignoring
2020-05-09 03:07:40.546401 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/canberradams/canberradams.py
2020-05-09 03:07:40.570259 INFO AppDaemon: Initializing app canberra_dams using class Get_ACT_Dams from module canberradams
2020-05-09 03:07:40.571439 WARNING canberra_dams: ------------------------------------------------------------
2020-05-09 03:07:40.572107 WARNING canberra_dams: Unexpected error initializing app: canberra_dams:
2020-05-09 03:07:40.572797 WARNING canberra_dams: ------------------------------------------------------------
2020-05-09 03:07:40.575477 WARNING canberra_dams: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-05-09 03:07:40.576728 WARNING canberra_dams: ------------------------------------------------------------
2020-05-09 03:07:40.577396 WARNING AppDaemon: Unable to find module canberra_dams - initialize() skipped
2020-05-09 03:07:40.578288 INFO AppDaemon: App initialization complete

Thanks
- shamal69

**Comment by simonhq** [comment]
Hi shamal69,

I don't actually know what that error is, but I checked the icon water website where I get the data and it is offline for maintenance at the moment. So can we wait to see if you still have the issue once it comes back online.

Thanks

Simon.

**Comment by simonhq** [comment]
Hi shamal69,

Have you had any luck setting this up now?

Simon.

**Comment by shamal69** [comment]
Hi Simon, I have run out of time at the moment, but it wasn't working :(

I'll have a try later in the week and let you know how I go ...

Cheers and thanks for the follow up!

**Comment by shamal69** [comment]
Hi Simon, can we reopen this?

I have tried loading the CanberraDams, Canberra Garbage and the Snowy Dams and  none are working - I am pretty sure it is something to do with my AppDaemon 4 config though, given they are all broken ....

Any ideas what the issue is?

Thanks


Jamie

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Installing collected packages: xmltodict
Successfully installed xmltodict-0.12.0
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:23:54] INFO: Starting AppDaemon...
2020-07-05 23:23:55.751676 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-07-05 23:23:55.752213 INFO AppDaemon: Python version is 3.8.2
2020-07-05 23:23:55.753105 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-07-05 23:23:55.753534 INFO AppDaemon: Added log: AppDaemon
2020-07-05 23:23:55.753938 INFO AppDaemon: Added log: Error
2020-07-05 23:23:55.754267 INFO AppDaemon: Added log: Access
2020-07-05 23:23:55.754744 INFO AppDaemon: Added log: Diag
2020-07-05 23:23:55.836190 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-07-05 23:23:55.866159 INFO HASS: HASS Plugin Initializing
2020-07-05 23:23:55.866657 INFO HASS: HASS Plugin initialization complete
2020-07-05 23:23:55.868079 INFO AppDaemon: HTTP is disabled             *** THIS IS WEIRD !!! ***
2020-07-05 23:23:55.876049 INFO HASS: Connected to Home Assistant 0.111.3
2020-07-05 23:23:55.898127 INFO HASS: Evaluating startup conditions
2020-07-05 23:23:55.902167 INFO AppDaemon: App 'canberra_dams' added
2020-07-05 23:23:55.902827 INFO AppDaemon: App 'act_garbage' added
2020-07-05 23:23:55.903311 INFO AppDaemon: App 'snowy_dams' added
2020-07-05 23:23:55.904466 INFO AppDaemon: Found 3 total apps
2020-07-05 23:23:55.905194 INFO AppDaemon: Starting Apps with 3 workers and 3 pins
2020-07-05 23:23:55.911860 INFO AppDaemon: Got initial state from namespace default
2020-07-05 23:23:57.911387 INFO AppDaemon: Scheduler running in realtime
2020-07-05 23:23:57.914360 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-07-05 23:23:57.914831 INFO AppDaemon: Adding /config/appdaemon/apps/config-check to module import path
2020-07-05 23:23:57.915161 INFO AppDaemon: Adding /config/appdaemon/apps/act_garbage to module import path
2020-07-05 23:23:57.915652 INFO AppDaemon: Adding /config/appdaemon/apps/snowydams to module import path
2020-07-05 23:23:57.916071 INFO AppDaemon: Adding /config/appdaemon/apps/canberradams to module import path
2020-07-05 23:23:57.921193 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/config-check/checkconfig.py - ignoring
2020-07-05 23:23:57.923026 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/act_garbage/act_garbage.py
2020-07-05 23:23:57.930387 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/snowydams/snowydams.py
2020-07-05 23:23:57.943067 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/canberradams/canberradams.py
2020-07-05 23:23:57.947066 INFO AppDaemon: Initializing app canberra_dams using class Get_ACT_Dams from module canberradams
2020-07-05 23:23:57.948269 WARNING canberra_dams: ------------------------------------------------------------
2020-07-05 23:23:57.948638 WARNING canberra_dams: Unexpected error initializing app: canberra_dams:
2020-07-05 23:23:57.949017 WARNING canberra_dams: ------------------------------------------------------------
2020-07-05 23:23:57.950662 WARNING canberra_dams: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-07-05 23:23:57.951061 WARNING canberra_dams: ------------------------------------------------------------
2020-07-05 23:23:57.951299 INFO AppDaemon: Initializing app act_garbage using class Get_ACT_Garbage from module act_garbage
2020-07-05 23:23:57.952366 WARNING act_garbage: ------------------------------------------------------------
2020-07-05 23:23:57.952619 WARNING act_garbage: Unexpected error initializing app: act_garbage:
2020-07-05 23:23:57.953015 WARNING act_garbage: ------------------------------------------------------------
2020-07-05 23:23:57.953366 WARNING act_garbage: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-07-05 23:23:57.953669 WARNING act_garbage: ------------------------------------------------------------
2020-07-05 23:23:57.953917 INFO AppDaemon: Initializing app snowy_dams using class Get_Snowy_Dams from module snowydams
2020-07-05 23:23:57.954820 WARNING snowy_dams: ------------------------------------------------------------
2020-07-05 23:23:57.955195 WARNING snowy_dams: Unexpected error initializing app: snowy_dams:
2020-07-05 23:23:57.955429 WARNING snowy_dams: ------------------------------------------------------------
2020-07-05 23:23:57.955907 WARNING snowy_dams: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-07-05 23:23:57.956121 WARNING snowy_dams: ------------------------------------------------------------
2020-07-05 23:23:57.956676 WARNING AppDaemon: Unable to find module canberra_dams - initialize() skipped
2020-07-05 23:23:57.957193 WARNING AppDaemon: Unable to find module act_garbage - initialize() skipped
2020-07-05 23:23:57.957689 WARNING AppDaemon: Unable to find module snowy_dams - initialize() skipped
2020-07-05 23:23:57.958468 INFO AppDaemon: App initialization complete

**Comment by shamal69** [comment]
Hi Simon

I have AppDaemon sorted now ... that is a feat in itself !!!

I am now at the point where I am getting the Garbage Collection information and the Snowy Dams, but not the Canberra ones ...

Any ideas here?

2020-07-06 00:45:41.710552 INFO AppDaemon: New client Admin Browser connected
2020-07-06 00:45:41.794485 WARNING canberra_dams: ------------------------------------------------------------
2020-07-06 00:45:41.795332 WARNING canberra_dams: Unexpected error running initialize() for canberra_dams
2020-07-06 00:45:41.795897 WARNING canberra_dams: ------------------------------------------------------------
2020-07-06 00:45:41.797767 WARNING canberra_dams: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/canberradams/canberradams.py", line 50, in initialize
    self.load()
  File "/config/appdaemon/apps/canberradams/canberradams.py", line 104, in load
    dcap = float(drcap) / (100 - float(dper)) * 100
ZeroDivisionError: float division by zero
2020-07-06 00:45:41.799243 WARNING canberra_dams: ------------------------------------------------------------

Cheers!

**Comment by simonhq** [comment]
Hi shamal69,

Glad to see it is getting close. The Canberra Dams app gets its information from the icon water website, which was down for maintenance over the weekend. If you restart appdaemon completely it will reset everything and you should be able to see the dam information.

let me know how you go

Simon
